name: itsytv
options:
  deploymentTarget:
    macOS: "14.0"
  bundleIdPrefix: com.itsytv
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

configs:
  Debug: debug
  Debug-AppStore: debug
  Release: release
  Release-AppStore: release

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: R892A93W42
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

packages:
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    from: "1.28.0"
  SRP:
    url: https://github.com/adam-fowler/swift-srp.git
    from: "2.1.0"

schemes:
  itsytv:
    build:
      targets:
        itsytv: all
        itsytvTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - itsytvTests
    archive:
      config: Release
  itsytv-appstore:
    build:
      targets:
        itsytv: all
    run:
      config: Debug-AppStore
    test:
      config: Debug-AppStore
    archive:
      config: Release-AppStore

targets:
  itsytv:
    type: application
    platform: macOS
    sources:
      - path: itsytv
        excludes:
          - "**/*.proto"
          - itsytv.entitlements
          - itsytv-direct.entitlements
    settings:
      base:
        INFOPLIST_FILE: itsytv/Info.plist
        CODE_SIGN_ENTITLEMENTS: itsytv/itsytv.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.itsytv.app
        PRODUCT_NAME: Itsytv
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.4.3"
        CURRENT_PROJECT_VERSION: "16"
        ENABLE_HARDENED_RUNTIME: true
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: itsytv/itsytv-direct.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: itsytv/itsytv-direct.entitlements
        Debug-AppStore:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE
        Release-AppStore:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE
    dependencies:
      - package: SwiftProtobuf
      - package: SRP
        product: SRP

  itsytvTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
      - path: itsytv
        excludes:
          - itsytvApp.swift
          - UI/**
          - AppIntents/**
          - "**/*.proto"
    dependencies:
      - package: SwiftProtobuf
      - package: SRP
        product: SRP
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.itsytv.tests
        PRODUCT_MODULE_NAME: itsytv
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: ""
